//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_OnlineTaxibooking.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class contact
    {
        public int Contact_Id { get; set; }
        [Display(Name ="Customer name")]
        public string Cust_name { get; set; }
        [Display(Name ="Customer email")]
        public string Cust_email { get; set; }
        [Display(Name ="Mobile no")]
        public string Cust_no { get; set; }
        [Display(Name ="Message")]
        public string Message { get; set; }
    }
}
